
package at.ac.tuwien.webservice.client.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BakeryService", targetNamespace = "http://service.webservice.tuwien.ac.at/", wsdlLocation = "http://localhost:8080/bakery?wsdl")
public class BakeryService
    extends Service
{

    private final static URL BAKERYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(at.ac.tuwien.webservice.client.service.BakeryService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = at.ac.tuwien.webservice.client.service.BakeryService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/bakery?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/bakery?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BAKERYSERVICE_WSDL_LOCATION = url;
    }

    public BakeryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BakeryService() {
        super(BAKERYSERVICE_WSDL_LOCATION, new QName("http://service.webservice.tuwien.ac.at/", "BakeryService"));
    }

    /**
     * 
     * @return
     *     returns Bakery
     */
    @WebEndpoint(name = "BakeryPort")
    public Bakery getBakeryPort() {
        return super.getPort(new QName("http://service.webservice.tuwien.ac.at/", "BakeryPort"), Bakery.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Bakery
     */
    @WebEndpoint(name = "BakeryPort")
    public Bakery getBakeryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.tuwien.ac.at/", "BakeryPort"), Bakery.class, features);
    }

}
